### ISSUE TITLE
Apostrophe bug

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/spotiyt-server#9]
Greetings, @alexmercerind!

I found a funny bug. If we try to find a track with apostrophe in its name, an empty title will be shown.

Example: "The Cure - I don't know what's going on":

![IMG_20200907_111448.jpg](https://user-images.githubusercontent.com/64320078/92347828-5f076880-f0fb-11ea-9c79-37aaf4b7cca5.jpg)

Response (https://harmonoid-ru.herokuapp.com/search?keyword=the+cure+i+don%27t+know+&mode=track&limit=20&offset=0):

![IMG_20200907_111743.jpg](https://user-images.githubusercontent.com/64320078/92347975-c9200d80-f0fb-11ea-84bc-8622d213d811.jpg)

I'm not sure if the backend is the problem, but I'll check it out as soon as I get home.

Thanks!

**Comment by alexmercerind** [comment]
👋 @raitonoberu !

Haha, actually yeah, it is not a problem in the backend.
You caught it right, actually I did this because Spotify had a habit of adding "(Deluxe Edition)" to the end of the album names.
So, what I did at the time of rendering is as follows (Obviously it was in dart, I'm using python below for explaining):

```python
# Assuming that albumName is the name of album
albumName = albumName.split(")")[0].trim()
# This removed the "(Deluxe Edition)" from all the album names as it caused my UI to distort sometimes.
```
But, now I'll fix this as you are getting problem & other people might get into trouble aswell.

Thankyou.

**Comment by raitonoberu** [comment]
Oh, right... Apostrophe is not the problem.

**Comment by alexmercerind** [comment]
Don't worry next release is going to be big & will bring many bug fixes and massive performance improvements.

**Comment by alexmercerind** [comment]
And, will you change the name of repository as there is no role of Spotify now? (I'm asking because if you do, then let me know as I have to modify the about section of the app then) 👌
